# Generated by Django 5.2.12 on 2026-04-05 16:51

import django.db.models.deletion
from django.db import migrations, models


def delete_orphaned_admin_logs(apps, schema_editor):
    """Remove admin log rows pointing to deleted users before SQLite FK checks."""
    connection = schema_editor.connection
    vendor = connection.vendor

    user_table = 'accounts_account'
    if vendor == 'postgresql':
        sql = f'''
            DELETE FROM django_admin_log
            WHERE user_id IN (
                SELECT l.user_id
                FROM django_admin_log l
                LEFT JOIN {user_table} u ON l.user_id = u.id
                WHERE u.id IS NULL
            )
        '''
    else:
        sql = f'''
            DELETE FROM django_admin_log
            WHERE user_id IN (
                SELECT user_id
                FROM django_admin_log
                WHERE user_id NOT IN (SELECT id FROM {user_table})
            )
        '''

    with connection.cursor() as cursor:
        cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgallery_image_nullable'),
    ]

    operations = [
        migrations.RunPython(delete_orphaned_admin_logs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to='photos/products/gallery/'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='store.product'),
        ),
    ]
